site_name: DevOpsCode.fs
nav:
  - Home:
    - index.md
  - Ansible:
    - Setup:
      - Installation: ansible/setup/installation.md
      - Configuration: ansible/setup/configuration.md
    - Mémento:
      - Array: ansible/memento/array.md
      - Builtin: ansible/memento/builtin.md
      - Calcul: ansible/memento/calcul.md
      - Date: ansible/memento/date.md
      - Dictionnary: ansible/memento/dictionary.md
      - Error: ansible/memento/error.md
      - File: ansible/memento/file.md
      - Lookup: ansible/memento/lookup.md
      - Loop: ansible/memento/loop.md
      - Vars: ansible/memento/vars.md
  - Homelab:
    - Proxmox: proxmox/proxmox.md
    - Debian: debian/minidebian.md
    - RedHat: redhat/xfcexrdpredhat.md
    - Mkdoc: debian/installmkdocs.md
    - Github: debian/githubpages.md
    - VsCode: vscode/installvscode.md
  - Markdown:
    - Syntax:
      - Markdown: markdown/syntax/syntax.md
      - Material Theme:  markdown/syntax/material.md
      - Tests: markdown/syntax/test.md
    - Mkdocs:
      - Configuration:
        - markdown/mkdocs/configuration/index.md
      - Theme Material for Mkdocs:
        - markdown/mkdocs/material/configuration/icons.md
        - markdown/mkdocs/material/configuration/mkdocs.md
        - markdown/mkdocs/material/configuration/extracss.md
        - markdown/mkdocs/material/exemple.md
    - Mermaid:
      - Exemples:
        - markdown/mermaid/graph.md
        - markdown/mermaid/flowchart.md
        - markdown/mermaid/gitgraph.md
        - markdown/mermaid/erdiagram.md
        - markdown/mermaid/gantt.md
        - markdown/mermaid/journey.md
        - markdown/mermaid/pie.md
        - markdown/mermaid/sequencediagram.md
  - Code:
    - code/ASCII_Encoding_Reference.md
    - code/URL_Encoding_Reference.md
    - code/Encodage_Html.md
  - About: about.md
theme:
  #name: readthedocs
  name: material
  custom_dir: material/overrides
  highlightjs: true
  hljs_languages:
    - yaml
  # titles_only: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3
  # - pymdownx.arithmatex:
  #    generic: true
  #- pymdownx.betterem:
  #    smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  #- pymdownx.magiclink:
  #    normalize_issue_symbols: true
  #    repo_url_shorthand: true
  #    user: squidfunk
  #    repo: mkdocs-material
  - pymdownx.snippets
#      auto_append:
#        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  # - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox
extra_css:
  - stylesheets/extra.css

hooks:
  - material/overrides/hooks/shortcodes.py
